" When started as "evim", evim.vim will already have done these settings.
if v:progname =~? "evim"
  finish
endif

" Use Vim settings, rather then Vi settings (much better!).
" This must be first, because it changes other options as a side effect.
set nocompatible

set autoindent      " always set autoindenting on

filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'
Plugin 'candy.vim'
Plugin 'vim-scripts/desert256.vim'
Plugin 'vim-scripts/comments.vim'
call vundle#end()            " required
filetype plugin indent on    " required
syntax on


set backspace=indent,eol,start

if has("vms")
  set nobackup      " do not keep a backup file, use versions instead
  else
    set backup        " keep a backup file
endif

set history=50      " keep 50 lines of command line history
set ruler       " show the cursor position all the time
set showcmd     " display incomplete commands
set incsearch       " do incremental searching

" Switch syntax highlighting on, when the terminal has colors
" Also switch on highlighting the last used search pattern.
if &t_Co > 2 || has("gui_running")
  syntax on
  set hlsearch
else
  syntax on
endif

"Tab
""""""""""""""""""""""""""
set tabstop=4
set expandtab
"set softtabstop=4
"python tab
""""""""""""""""""
"shift left or right together >
set shiftwidth=4

"color
set t_Co=256
if &t_Co == 256 || has('gui_running')
    colorscheme desert256   " Or some other high-color scheme
else
    colorscheme desert      " Or some other low-color scheme
endif
"
